# Generated by Django 5.1.1 on 2024-09-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='created',
        ),
    ]
